
// This file has been generated by the GUI designer. Do not modify.
namespace HighFlyers.GCS
{
	public partial class Communication
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBoxEntry portsComboBox;
		private global::Gtk.Button rescanPortsButton;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.ComboBox baudRateComboBox;
		private global::Gtk.Button openCloseButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HighFlyers.GCS.Communication
			global::Stetic.BinContainer.Attach (this);
			this.Name = "HighFlyers.GCS.Communication";
			// Container child HighFlyers.GCS.Communication.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Select port:");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.portsComboBox = global::Gtk.ComboBoxEntry.NewText ();
			this.portsComboBox.Name = "portsComboBox";
			this.hbox2.Add (this.portsComboBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.portsComboBox]));
			w2.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.rescanPortsButton = new global::Gtk.Button ();
			this.rescanPortsButton.CanFocus = true;
			this.rescanPortsButton.Name = "rescanPortsButton";
			this.rescanPortsButton.UseUnderline = true;
			this.rescanPortsButton.Label = global::Mono.Unix.Catalog.GetString ("Rescan");
			this.hbox2.Add (this.rescanPortsButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.rescanPortsButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Baud rate:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.baudRateComboBox = global::Gtk.ComboBox.NewText ();
			this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("9600"));
			this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("115200"));
			this.baudRateComboBox.Name = "baudRateComboBox";
			this.baudRateComboBox.Active = 0;
			this.hbox1.Add (this.baudRateComboBox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.baudRateComboBox]));
			w6.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.openCloseButton = new global::Gtk.Button ();
			this.openCloseButton.CanFocus = true;
			this.openCloseButton.Name = "openCloseButton";
			this.openCloseButton.UseUnderline = true;
			this.openCloseButton.Label = global::Mono.Unix.Catalog.GetString ("Open port");
			this.vbox1.Add (this.openCloseButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.openCloseButton]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.rescanPortsButton.Clicked += new global::System.EventHandler (this.OnRescanPortsButtonClicked);
			this.openCloseButton.Clicked += new global::System.EventHandler (this.OnOpenCloseButtonClicked);
		}
	}
}
