
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.HPaned hpaned3;
	private global::Gtk.VBox vbox7;
	private global::HighFlyers.GCS.Communication communicationWidget;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Label label4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView receivedDataTextView;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Label label5;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView sentDataTextView;
	private global::Gtk.Image image1;
	private global::Gtk.Label label3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hpaned3 = new global::Gtk.HPaned ();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 338;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.communicationWidget = new global::HighFlyers.GCS.Communication ();
		this.communicationWidget.Events = ((global::Gdk.EventMask)(256));
		this.communicationWidget.Name = "communicationWidget";
		this.vbox7.Add (this.communicationWidget);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.communicationWidget]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 189;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Received data:");
		this.vbox5.Add (this.label4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label4]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.receivedDataTextView = new global::Gtk.TextView ();
		this.receivedDataTextView.CanFocus = true;
		this.receivedDataTextView.Name = "receivedDataTextView";
		this.GtkScrolledWindow.Add (this.receivedDataTextView);
		this.vbox5.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
		w4.Position = 1;
		this.hpaned1.Add (this.vbox5);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox5]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Sent data:");
		this.vbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label5]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.sentDataTextView = new global::Gtk.TextView ();
		this.sentDataTextView.CanFocus = true;
		this.sentDataTextView.Name = "sentDataTextView";
		this.GtkScrolledWindow1.Add (this.sentDataTextView);
		this.vbox6.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow1]));
		w8.Position = 1;
		this.hpaned1.Add (this.vbox6);
		this.vbox7.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hpaned1]));
		w10.Position = 1;
		this.hpaned3.Add (this.vbox7);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.vbox7]));
		w11.Resize = false;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.hpaned3.Add (this.image1);
		this.notebook1.Add (this.hpaned3);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Devices");
		this.notebook1.SetTabLabel (this.hpaned3, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w14.Position = 0;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 656;
		this.DefaultHeight = 451;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
